#!/bin/bash

if [ "$(grep -Ei 'debian|buntu|mint|raspbian|elementary' /etc/*release)" ]; then
	sudo apt update
	sudo apt upgrade -y
	sudo apt dist-upgrade -y
	sudo apt remove -y
	sudo apt autoremove -y
	sudo apt-get install build-essential -y

	for i in 	certbot python3-certbot-nginx python3 python3-dev \
		python3-pip build-essential libssl-dev musl-dev libffi-dev \
		rustc rust-doc rust-gdb cargo nano htop apt-transport-https \
		ca-certificates curl software-properties-common nginx php-fpm \
		wget curl zsh git git-core gnome-shell ubuntu-session gnome-boxes \
		network-manager make snap snapd flatpak meson sassc libglib2.0-dev \
		libxml2-utils csh tcsh; \
	do sudo apt-get build-dep $i -y; done

	sudo apt upgrade -y
	sudo apt dist-upgrade -y
	sudo apt remove -y
fi

dir=~/.oh-my-zsh/
if [ -d "$dir" -a ! -h "$dir" ]
then
	tput bold; tput setaf 2;
	echo "Oh my zsh already installed."
	tput sgr0;
else
	sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
fi
