#!/bin/bash

if [ "$(grep -Ei 'debian|buntu|mint|raspbian|elementary' /etc/*release)" ]; then
	sudo apt update
	sudo apt upgrade -y
	sudo apt dist-upgrade -y
	sudo apt remove -y
	sudo apt autoremove -y
	sudo apt-get install build-essential -y

	for i in	certbot python3-certbot-nginx python3 python3-dev python3-pip build-essential libssl-dev musl-dev \
	  libffi-dev rustc rust-doc rust-gdb cargo nano htop apt-transport-https ca-certificates curl \
	  software-properties-common nginx php-fpm wget curl zsh git git-core gnome-shell ubuntu-session gnome-boxes \
    network-manager make snap snapd flatpak meson sassc libglib2.0-dev install ca-certificates git build-essential \
    cmake gcc g++ libkf5config-dev libkf5auth-dev libkf5package-dev libkf5declarative-dev libkf5coreaddons-dev \
    libkf5dbusaddons-dev libkf5kcmutils-dev libkf5i18n-dev libkf5plasma-dev libqt5core5a libqt5widgets5 libqt5gui5 \
    libqt5qml5 extra-cmake-modules qtbase5-dev libkf5notifications-dev qml-module-org-kde-kirigami2 \
    qml-module-qtquick-dialogs qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qt-labs-settings \
    qml-module-qt-labs-folderlistmodel gettext libxml2-utils csh tcsh;
	do 
	  sudo apt-get build-dep $i -y; 
  done

	sudo apt upgrade -y
	sudo apt dist-upgrade -y
	sudo apt remove -y
fi


if command -v dnf &> /dev/null 
then
	if [ "$(grep -Ei 'redhat|fedora|centos' /etc/*release)" ]; then
	  
	  sudo dnf clean all
	  sudo dnf check-update
	  sudo dnf upgrade -y
	  
	  for i in git gcc g++ cmake kf5-ki18n-devel kf5-kauth-devel kf5-kconfig-devel kf5-kpackage-devel \
	  kf5-kcoreaddons-devel kf5-kdbusaddons-devel extra-cmake-modules kf5-knotifications-devel qt5-qtquickcontrols2-devel \
	  kf5-kconfigwidgets-devel kf5-kcmutils-devel kf5-plasma-devel cmake gettext qt5-qtbase-devel gcc-c++ \
	  kf5-kdeclarative-devel qt5-qtquickcontrols qt5-qtquickcontrols2;
    do
      sudo dnf install $i -y;
    done
    
    sudo dnf clean all
    sudo dnf check-update
    sudo dnf upgrade -y

	fi
fi

dir=~/.oh-my-zsh/
if [ -d "$dir" -a ! -h "$dir" ]
then
	tput bold; tput setaf 2;
	echo "Oh my zsh already installed."
	tput sgr0;
else
	sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
fi
