#!/bin/bash

dir="$1"
newfilename="$1".tar.gz

[ $# -eq 0 ] && { echo "Usage: $0 dir-name"; exit 1; }

if [ -d "$dir" -a ! -h "$dir" ]
then
   tput bold; tput setaf 2;
   echo "$dir found and now compressing to $newfilename, please wait..."
   
   printf "\nSize Information From:\n"
   tput setaf 1;
   du -hs "$dir"

   tput bold; tput setaf 2;
   printf "\nTime Information"
   tput setaf 1;
   time tar --use-compress-program="pigz -k -9 " -cf "$newfilename" "$dir"

   tput bold; tput setaf 2;
   printf "\nSize Information To:\n"
   tput setaf 1;
   du -hs "$newfilename"
else
   tput sgr0;tput setaf 1;
   echo "Error: $dir not found or is symlink to $(readlink -f ${dir})."
fi
tput sgr0;
