#!/bin/tcsh -f

#foreach item ( $argv )
	
	set namepart = `echo $argv | rev | cut -d"." -f2- | rev`
	echo $namepart
	
	set filepart = `echo $argv | rev | cut -d"." -f1  | rev`
	echo $filepart
	
	set newname = "$namepart.hvec.$filepart"
	echo making $newname
	
	#ffmpeg \
	#-i "$argv" \
	#-c:v libx265 \
	#-preset slow \
	#-x265-params crf=22 \
	#-c:a libmp3lame \
	#-b:a 128k \
	#"$newname"
	
	ffmpeg \
	-y \
	-threads 8 \
	-hwaccel nvdec \
	-hwaccel_output_format cuda \
	-i "$argv" \
	-c:v hevc_nvenc \
	-rc vbr -tune:v ll \
	#-rc-lookahead:v 32 \
	-cq:v 21 \
	#-qmin 24  \
	#-qmax 24 \
	-profile:v main10 \
	#-pix_fmt p010le \
	-b:v 0 \
	-maxrate:v 5M \
	-bufsize:v 8M \
	#-qp 28 \
	#-map 0 \
	-v verbose "$newname"
	
	#mv "$argv" "$argv".spare

#end
