#!/bin/zsh

if command -v snap &> /dev/null 
then
	sudo snap refresh
fi


ZSHRCFILE=~/.zshrc
if [ -f "$ZSHRCFILE" ]; then
	~/.oh-my-zsh/tools/./upgrade.sh
	# omz update
fi

if ! command -v pihole &> /dev/null 
then
	tput bold; tput setaf 2;
	echo "Not Raspberry Pi, will not try to update pihole."
	tput sgr0;
else
	pihole -up
fi

# BIG COMMENT
: <<'END'
ARCH_SCRIPT=`uname -m`
ARCH_SCRIPT_PI=arm

if [[ "$ARCH_SCRIPT" == *"$ARCH_SCRIPT_PI"* ]]
then
	pihole -up
else
	tput bold; tput setaf 2;
	echo "Not Raspberry Pi, will not try to update pihole."
	tput sgr0;
fi
END

NOT_SET='unset'
SET='set'

PROG_APT=$NOT_SET
PROG_DNF=$NOT_SET
PROG_PACMAN=$NOT_SET
PROG_ZYPPER=$NOT_SET

if command -v apt &> /dev/null 
then
	if [ "$(grep -Ei 'debian|buntu|mint|raspbian|elementary' /etc/*release)" ]; then
		PROG_APT=$SET
	fi
fi


if command -v dnf &> /dev/null 
then
	if [ "$(grep -Ei 'redhat|fedora|centos' /etc/*release)" ]; then
		PROG_DNF=$SET
	fi
fi


if command -v pacman &> /dev/null 
then
	if [ "$(grep -Ei 'arch|manjaro' /etc/*release)" ]; then
		PROG_PACMAN=$SET
	fi
fi

if command -v zypper &> /dev/null 
then
	if [ "$(grep -Ei 'opensuse' /etc/*release)" ]; then
		PROG_ZYPPER=$SET
	fi
fi

tput bold; tput setaf 1;

if [[ "$PROG_APT" == "$SET" ]]
then
	echo $PROG_APT apt
	tput sgr0;
	sudo apt update
	sudo apt upgrade -y
	sudo apt dist-upgrade -y
	sudo apt remove -y
fi

if [[ "$PROG_PACMAN" == "$SET" ]]
then
	echo $PROG_PACMAN pacman
	tput sgr0;
	sudo pacman -Syu
fi

if [[ "$PROG_DNF" == "$SET" ]]
then
	echo $PROG_DNF dnf
	tput sgr0;
	sudo dnf clean all
	sudo dnf check-update
	sudo dnf upgrade -y
fi

if [[ "$PROG_ZYPPER" == "$SET" ]]
then
	echo $PROG_ZYPPER zypper
	tput sgr0;
	sudo zypper update -y
fi

tput sgr0;
